extend_default_excludes = true
exclude_patterns = [
    # Add your custom exclusions here
    # "vendor/",
    # "third_party/",
]

# Minimum lines for duplicate detection
min_duplicate_lines = 6

# Entropy thresholds
[entropy_thresholds]
good = 0.3     # Below this is good
warning = 0.6  # Below this is warning, above is poor

# Component weights (must sum to 1.0)
[weights]
complexity = 0.25
duplication = 0.25
size = 0.20
coverage = 0.05
dependencies = 0.15
change = 0.10

# Analysis parameters
[analysis]
git_history_days = 180
max_file_size = 10000  # Lines before warning
complexity_threshold = 10  # Cyclomatic complexity threshold
