"""auto migration

Revision ID: 177f5e3bc278
Revises: 5bcf6394c136
Create Date: 2025-06-17 09:37:05.122441

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "177f5e3bc278"
down_revision: str | None = "5bcf6394c136"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    op.drop_table("app_users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_users",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("email", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("password", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("username", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("first_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("last_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("role", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("last_login", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("password_reset_token", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("password_reset_expires", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("two_factor_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("two_factor_secret", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="app_users_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("last_activity", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("ip_address", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("user_agent", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("device_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_valid", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("revoked_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("platform", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("browser", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["app_users.id"], name=op.f("sessions_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("sessions_pkey")),
    )
    # ### end Alembic commands ###
