"""auto migration

Revision ID: 27cdc85628fb
Revises: 3d5344a6a879
Create Date: 2025-06-17 11:45:56.977742

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "27cdc85628fb"
down_revision: str | None = "3d5344a6a879"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
