"""auto migration

Revision ID: 3d5344a6a879
Revises: 177f5e3bc278
Create Date: 2025-06-17 10:53:15.154297

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "3d5344a6a879"
down_revision: str | None = "177f5e3bc278"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
