"""auto migration

Revision ID: b961dcb63ef1
Revises:
Create Date: 2025-06-17 13:47:48.460086

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b961dcb63ef1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("adj_close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "date", name="uix_symbol_date"),
    )
    op.create_index(op.f("ix_stock_data_date"), "stock_data", ["date"], unique=False)
    op.create_index(op.f("ix_stock_data_symbol"), "stock_data", ["symbol"], unique=False)
    op.create_table(
        "tracked_stock",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("last_pull_date", sa.DateTime(), nullable=False),
        sa.Column("last_pull_status", sa.String(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", name="uix_symbol"),
    )
    op.create_index(op.f("ix_tracked_stock_symbol"), "tracked_stock", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracked_stock_symbol"), table_name="tracked_stock")
    op.drop_table("tracked_stock")
    op.drop_index(op.f("ix_stock_data_symbol"), table_name="stock_data")
    op.drop_index(op.f("ix_stock_data_date"), table_name="stock_data")
    op.drop_table("stock_data")
    # ### end Alembic commands ###
