"""auto migration

Revision ID: f9a64abef2b9
Revises: 8ce2f48051df
Create Date: 2025-06-20 17:56:58.195105

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f9a64abef2b9"
down_revision: str | None = "8ce2f48051df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
